FROM ubuntu:xenial

RUN apt-get update && \
  apt-get install -y curl && \
  echo "deb http://storage.googleapis.com/tensorflow-serving-apt stable tensorflow-model-server tensorflow-model-server-universal" | tee /etc/apt/sources.list.d/tensorflow-serving.list && \
  curl https://storage.googleapis.com/tensorflow-serving-apt/tensorflow-serving.release.pub.gpg | apt-key add - && \
  apt-get update && \
  apt-get install tensorflow-model-server

COPY /models/tf_models/model/ /models/tf_models

CMD tensorflow_model_server --port=8500 --rest_api_port=${PORT} --model_name=model --model_base_path=/models/tf_models